<?php
// This file generated by Propel 1.7.1 convert-conf target
return array (
  'BaseCondominio' => 'condominio/om/BaseCondominio.php',
  'BaseCondominioPeer' => 'condominio/om/BaseCondominioPeer.php',
  'BaseCondominioQuery' => 'condominio/om/BaseCondominioQuery.php',
  'Condominio' => 'condominio/Condominio.php',
  'CondominioPeer' => 'condominio/CondominioPeer.php',
  'CondominioQuery' => 'condominio/CondominioQuery.php',
  'CondominioTableMap' => 'condominio/map/CondominioTableMap.php',
);